version: '3.1'
networks:
  rede_interna_container:
    external: true
services:
  db:
    container_name: postgres
    image: postgres:13.4-alpine
    restart: always
    user: postgres
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: ecommerce
      POSTGRES_USER: django
      POSTGRES_PASSWORD: djangosenha
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - .postgres_data:/data/db
    networks:
      - rede_interna_container

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_DEFAULT_SERVER_MODE: 'False'
    ports:
      - 5050:80
    networks:
      - rede_interna_container
  web:
    container_name: django
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: django:django
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - pgadmin
    networks:
      - rede_interna_container





