version: '3.1'

services:

  db:
    image: postgres:13.4-alpine
    restart: always
    user: postgres
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: ecommerce
      POSTGRES_USER: django
      POSTGRES_PASSWORD: djangosenha
    ports:
      - 5432:5432
    volumes:
      - .postgres_data:/data/db



  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_DEFAULT_SERVER_MODE: 'False'
    ports:
      - 5050:80
