# Generated by Django 4.1.6 on 2023-02-11 12:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='11022023/091804', max_length=50, unique=True, verbose_name='Código do carrinho')),
                ('ativo', models.BooleanField(default=True, verbose_name='Carrinho ativo')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrinhos_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carrinho de compra',
                'verbose_name_plural': 'Carrinhos de compra',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, verbose_name='Preço')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Score')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagens_products', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='OrderClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_order', models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('finalizado', 'Finalizado'), ('outros', 'Outros')], default='pendente', max_length=10, verbose_name='Status do Pedido')),
                ('value_itens', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, verbose_name='Valor dos Itens')),
                ('value_addition', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, verbose_name='Valor de acrescimo')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, verbose_name='Valor total')),
                ('register_date', models.DateTimeField(auto_now=True)),
                ('checkout_date', models.DateTimeField(blank=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='orders_cart', to='shop.cartsmodel')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ItensCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.PositiveSmallIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cart', to='shop.cartsmodel')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_cart_p', to='shop.productsmodel')),
            ],
        ),
    ]
