# Generated by Django 4.1.6 on 2023-02-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartsmodel',
            name='code',
            field=models.CharField(blank=True, default='11022023/094508', max_length=50, unique=True, verbose_name='Código do carrinho'),
        ),
        migrations.AlterField(
            model_name='orderclients',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
